version: 2.1

jobs:
  lint-manifests:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/project
    steps:
      - run: make lint-step-manifests

  build-test-push:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    resource_class: xlarge
    working_directory: ~/project
    steps:
      - checkout
      #- run: TAG=${CIRCLE_TAG} BRANCH=${CIRCLE_BRANCH} make pushbase
      #- run: TAG=${CIRCLE_TAG} BRANCH=${CIRCLE_BRANCH} make pushall packall -j 8
      #- run: pyenv global 3.7.0
      #- run: pip install pyyaml
      #- run: TAG=${CIRCLE_TAG} BRANCH=${CIRCLE_BRANCH} make indexfile
      #- run: TAG=${CIRCLE_TAG} BRANCH=${CIRCLE_BRANCH} make validate-vendors

      - persist_to_workspace:
          root: .
          paths:
            - out
            - Makefile
            - vendors

  publish-manifest:
    docker:
      - image: google/cloud-sdk
    working_directory: /tmp/workspace
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
      - run: TAG=${CIRCLE_TAG} BRANCH=${CIRCLE_BRANCH} make publish-manifests-no-deps
      - run: TAG=${CIRCLE_TAG} BRANCH=${CIRCLE_BRANCH} make publish-vendors
          

workflows:
  version: 2
  build_and_test:
    jobs:
      - lint-manifests:
        filters:
          tags:
            only: /.*/
      - build-test-push:
          filters:
            tags:
              only: /.*/
      #- publish-manifest:
      #    context: development
      #    requires:
      #      - build-test-push
      #    filters:
      #      branches:
      #        only:
      #          master
