apiVersion: stackpulse.io/v1
kind: Step
metadata:
  name: "stackpulse_page"
  description: "Page a person using a phone call or SMS and receive an acknowledgment."
  vendor: stackpulse
  type: notification
envs:
  - name: PHONE_NUMBER
    description: "Phone number used for paging."
    type: "string"
    required: true
    example: "+15555555555"
  - name: MESSAGE
    description: "Text will be sent to destination."
    type: "string"
    required: true
    example: "System UI is not working."
  - name: TYPE
    description: "Flow type."
    type: "string"
    default: "PHONE_CALL"
    example: "PHONE_CALL"
    example: "SMS"

outputs:
  - name: acknowledged
    description: "Whether the person acknowledged the page. If the person did not acknowledge or any error occurred during the page, this will be false."
    type: "bool"
    example: 'true'